version: '3.8'
services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5433:5432'
    volumes:
      - db_other:/var/lib/postgresql/data
volumes:
  db_other:
